name: Hello

on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x activity.sh # my-other-script.sh
      - name: Run the scripts
        run: |
          ./activity.sh
        #   ./my-other-script.sh